services:
  d4g-vaultwarden:
    image: "vaultwarden/server:latest"
    container_name: "d4g-vaultwarden"
    environment:
      - SERVICE_FQDN_VAULTWARDEN={{ default_server_name }}
      - SIGNUPS_ALLOWED=false
      - ADMIN_TOKEN={{ vaultwarden_admin_token_argonized }}
      - SMTP_HOST=smtp-relay.brevo.com
      - SMTP_FROM=tech@dataforgood.fr
      - SMTP_PORT=587
      - SMTP_SECURITY=starttls
      - SMTP_USERNAME=hellodataforgood@gmail.com
      - SMTP_PASSWORD={{ smtp_password }}
      - DATABASE_URL={{ vaultwarden_postgresql_connection_string }}
      - SHOW_PASSWORD_HINT=false
    volumes:
      - ./data:/data
    networks:
      - d4g-internal
    healthcheck:
      test:
        - CMD
        - curl
        - "-f"
        - "http://localhost:80"
      interval: 2s
      timeout: 10s
      retries: 15
    restart: unless-stopped

networks:
  d4g-internal:
    external: true
